[tool.autopep8]
    max_line_length = 128
    in-place = true
    recursive = true
[tool.docformatter]
    recursive = true
    wrap-summaries = 120
    wrap-descriptions = 128
    in-place = true
    blank = true
[tool.mypy]
    files = ["deeplines/"]
    check_untyped_defs = true
    disallow_any_generics = true
    disallow_incomplete_defs = true
    disallow_untyped_defs = true
    ignore_missing_imports = true
    no_implicit_optional = true
    warn_unused_ignores = true
    warn_redundant_casts = true
[tool.coverage.run]
    plugins = ["covdefaults"]
